### ISSUE TITLE
How do I generate a Basic token?

### ISSUE THREAD

**Issue by SuperSonicHub1** [hyugogirubato/API-Crunchyroll-Beta#1]
Hey,
I'm assisting with creating a [new Crunchyroll extractor for youtube-dl](https://github.com/ytdl-org/youtube-dl/issues/29290) based on the beta. For the token endpoint, where does the Basic token **come from**?

**Comment by hyugogirubato** [comment]
Answered in this channel: https://github.com/ytdl-org/youtube-dl/issues/29290#issuecomment-870781173
