### ISSUE TITLE
Converting Media IDs

### ISSUE THREAD

**Issue by TanukiAI** [hyugogirubato/API-Crunchyroll-Beta#2]
Did you find any way to convert old media IDs (814376) to beta media IDs (GMKUX5583) just by using the beta api?
Unfortunately the RSS Feed only has old media IDs and I convert them with the old api, but the old api sucks hard as it sometimes just outputs random errors for no reason.

**Comment by hyugogirubato** [comment]
@TA40 
In the very first version of the app I used the old API, but I reviewed the working mode and I now use the new API completely, so all the id’s are the new id’s, I don’t use the old ones anymore. So I recommend two solutions: the first is simply to switch to the new version of the API, the second is to use both, that is to say to get the exact name of the series with the old API, then use the new search API to display the corresponding series id.

**Comment by TanukiAI** [comment]
I'd like to switch to the new API, but unfortunately it doesn't really have a good feed for new episodes.
I already use the old API to convert the media IDs. Just wanted to ask if you know a way to convert the media IDs with the **new** API ^^
Thanks tho!

**Comment by stefanodvx** [comment]
did you find a way to convert ids? @TanukiAI

**Comment by TanukiAI** [comment]
> did you find a way to convert ids? @TanukiAI

Nope.

**Comment by hyugogirubato** [comment]
There is a way to convert the old ids to the new ones, my api supports both versions of ids (if it still works) @TanukiAI
