### ISSUE TITLE
Method used to map APIs

### ISSUE THREAD

**Issue by samuraiexx** [hyugogirubato/API-Crunchyroll-Beta#3]
Hi, I would like to know how you discovered CR APIs and mapped them. Are there standard practices for doing that?
I tried to look at the network calls on their website but didn't see any calls to that API.

- I love your work, thank you very much for that.

**Comment by hyugogirubato** [comment]
@samuraiexx 
I use public and free software that is found to do web interception. If you want to have an overview or details you can search on youtube with the keyword "mitm"
